import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { architecture } from "./model.mjs";

const { root, modules } = architecture();
const destination = resolve(root, process.argv[2] ?? "docs/architecture/dependencies.mmd");
const portable = (path) => path.split(sep).join("/");
const area = (id) => {
  if (id.startsWith("action/src/")) return "action";
  if (id.startsWith("apps/review/src/features/")) return "review/features";
  if (id.startsWith("apps/review/src/shared/")) return "review/shared";
  if (id.startsWith("apps/review/src/")) return "review/entrypoints";
  if (id.startsWith("packages/agentlint/src/features/")) return "core/features";
  if (id.startsWith("packages/agentlint/src/domain/")) return "core/domain";
  if (id.startsWith("packages/agentlint/src/shared/infrastructure/")) return "core/infrastructure";
  if (id.startsWith("packages/agentlint/src/shared/pipeline/")) return "core/pipeline";
  if (id.startsWith("packages/agentlint/src/config/")) return "core/config";
  return "core/entrypoints";
};

const edges = new Map();
for (const module of modules.values()) {
  for (const dependency of module.dependencies) {
    const target = modules.get(dependency);
    if (target === undefined) continue;
    const from = area(module.id);
    const to = area(target.id);
    if (from === to) continue;
    edges.set(`${from}\0${to}`, [from, to]);
  }
}

const areas = new Set([...modules.values()].map((module) => area(module.id)));
const ids = new Map([...areas].toSorted().map((name, index) => [name, `n${index}`]));
const lines = [
  "%% Generated by `pnpm architecture:graph`; do not edit by hand.",
  "flowchart LR",
  ...[...ids].map(([name, id]) => `  ${id}["${name}"]`),
  ...[...edges.values()].toSorted().map(([from, to]) => `  ${ids.get(from)} --> ${ids.get(to)}`),
  "",
];
mkdirSync(dirname(destination), { recursive: true });
writeFileSync(destination, lines.join("\n"));
console.log(`Wrote ${portable(relative(root, destination))} (${edges.size} area dependencies).`);
